import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><div className="w-full min-h-screen flex flex-col font-main bg-back1 text-black">
        <Header></Header>
        {children}
      </div></body>
    </html>
  );
}
